spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
  redis:
    host: localhost
    port: 6379
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest